name: First workflow
on: workflow_dispatch 

jobs: 
  name: first workflow
  runs-on: ubuntu-latest 
  
  steps:
    - name: Print greeting
      run: echo "Hello World!"
  -name: Print goodbye
  run: echo "Done - bye!"

